### PR TITLE
CoffeeScript -> JS

### PR DESCRIPTION
**Pull request by TimvdLippe**
This PR updates all coffeescript files to JS ES6 to be compatible with Hubot 3.

### CODE REVIEW

**Comment by jjasghar** [comment]
Thanks!

**Comment by TimvdLippe** [comment]
@jjasghar Thanks for the merge! Could you release a new version of this package?

**Comment by jjasghar** [comment]
Sure, it's been a long time, but i'll make it happen.

**Comment by jjasghar** [comment]
done!

**Comment by TimvdLippe** [comment]
It is working, thanks!

**Pull request merged**
